// AminoVerse Neo4j Knowledge Graph Schema

// Create constraints for unique IDs
CREATE CONSTRAINT IF NOT EXISTS FOR (p:Protein) REQUIRE p.id IS UNIQUE;
CREATE CONSTRAINT IF NOT EXISTS FOR (d:Disease) REQUIRE d.id IS UNIQUE;
CREATE CONSTRAINT IF NOT EXISTS FOR (m:Drug) REQUIRE m.id IS UNIQUE;
CREATE CONSTRAINT IF NOT EXISTS FOR (v:Variant) REQUIRE v.id IS UNIQUE;

// Sample Protein Data - TP53
MERGE (p1:Protein {
  id: "P04637",
  name: "TP53",
  full_name: "Cellular tumor antigen p53",
  function: "Acts as a tumor suppressor by inducing growth arrest or apoptosis depending on the physiological circumstances and cell type.",
  description: "Tumor suppressor that regulates cell division by keeping cells from growing and dividing too fast or in an uncontrolled way.",
  sequence: "MEEPQSDPSVEPPLSQETFSDLWKLLPENNVLSPLPSQAMDDLMLSPDDIEQWFTEDPGPDEAPRMPEAAPPVAPAPAAPTPAAPAPAPSWPLSSSVPSQKTYQGSYGFRLGFLHSGTAKSVTCTYSPALNKMFCQLAKTCPVQLWVDSTPPPGTRVRAMAIYKQSQHMTEVVRRCPHHERCSDSDGLAPPQHLIRVEGNLRVEYLDDRNTFRHSVVVPYEPPEVGSDCTTIHYNYMCNSSCMGGMNRRPILTIITLEDSSGNLLGRNSFEVRVCACPGRDRRTEEENLRKKGEPHHELPPGSTKRALPNNTSSSPQPKKKPLDGEYFTLQIRGRERFEMFRELNEALELKDAQAGKEPGGSRAHSSHLKSKKGQSTSRHKKLMFKTEGPDSD"
});

MERGE (p2:Protein {
  id: "P38398",
  name: "BRCA1",
  full_name: "Breast cancer type 1 susceptibility protein",
  function: "Plays a central role in DNA repair by facilitating cellular responses to DNA damage.",
  description: "E3 ubiquitin-protein ligase that specifically mediates the formation of Lys-6-linked polyubiquitin chains and plays a central role in DNA repair by facilitating cellular responses to DNA damage.",
  sequence: "MDLSALRVEEVQNVINAMQKILECPICLELIKEPVSTKCDHIFCKFCMLKLLNQKKGPSQCPLCKNDITKRSLQESTRFSQLVEELLKIICAFQLDTGLEYANSYNFAKKENNSPEHLKDEVSIIQSMGYRNRAKRLLQSEPENPSLQETSLSVQLSNLGTVRTLRTKQRIQPQKTSVYIELGSDSSEDTVNKATYCSVGDQELLQITPQGTRDEISLDSAKKAACEFSETDVTNTEHHQPSNNDLNTTEKRAAERHPEKYQGSSVSNLHVEPCGTNTHASSLQHENSSLLLTKDRMNVEKAEFCNKSKQPGLARSQHNRWAGSKETCNDRRTPSTEKKVDLNADPLCERKEWNKQKLPCSENPRDTEDVPWITLNSSIQKVNEWFSRSDELLGSDDSHDGESESNAKVADVLDVLNEVDEYSGSSEKIDLLASDPHEALICKSERVHSKSVESNIEDKIFGKTYRKKASLPNLSHVTENLIIGAFVTEPQIIQERPLTNKLKRKRRPTSGLHPEDFIKKADLAVQKTPEMINQGTNQTEQNGQVMNITNSGHENKTKGDSIQNEKNPNPIESLEKESAFKTKAEPISSSISNMELELNIHNSKAPKKNRLRRKSSTRHIHALELVVSRNLSPPNCTELQIDSCSSSEEIKKKKYNQMPVRHSRNLQLMEGKEPATGAKKSNKPNEQTSKRHDSDTFPELKLTNAPGSFTKCSNTSELKEFVNPSLPREEKEEKLETVKVSNNAEDPKDLMLSGERVLQTERSVESSSISLVPGTDYGTQESISLLEVSTLGKAKTEPNKCVSQCAAFENPKGLIHGCSKDNRNDTEGFKYPLGHEVNHSRETSIEMEESELDAQYLQNTFKVSKRQSFAPFSNPGNAEEECATFSAHSGSLKKQSPKVTFECEQKEENQGKNESNIKPVQTVNITAGFPVVGQKDKPVDNAKCSIKGGSRFCLSSQFRGNETGLITPNKHGLLQNPYRIPPLFPIKSFVKTKCKKNLLEENFEEHSMSPEREMGNENIPSTVSTISRNNIRENVFKEASSSNINEVGSSTNEVGSSINEVGSSINEIGSSDENIQAELGRNRGPKLNAMLRLGVLQPEVYKQSLPGSNCKHPEIKKQEYEEVVQTVNTDFSPYLISDNLEQPMGSSHASQVCSETPDDLLDDGEIKEDTSFAENDIKESSAVFSKSVQKGELSRSPSPFTHTHLAQGYRRGAKKLESSEENLSSEDEELPCFQHLLFGKVNNIPSQSTRHSTVATECLSKNTEENLLSLKNSLNDCSNQVILAKASQEHHLSEETKCSASLFSSQCSELEDLTANTNTQDPFLIGSSKQMRHQSESQGVGLSDKELVSDDEERGTGLEENNQEEQSMDSNLGEAASGCESETSVSEDCSGLSSQSDILTTQQRDTMQHNLIKLQQEMAELEAVLEQHGSQPSNSYPSIISDSSALEDLRNPEQSTSEKAVLTSQKSSEYPISQNPEGLSADKFEVSADSSTSKNKEPGVERERPLFLSPEIKQSWANSSFCSLPTFNPGTEIANTKDGKLTAFEHTSILEPSKDKANLNVSKKEMDNKSLGNCSSTEQANEFLKPSSQCSLSVVGDETLSSPPRDLPQSPGTVDTFPTLIETSAATSDSGHSAAQTSPNSLSSPSADSTFIDTETAILDNSSGFNSVNSASDSPTGNSVTSVDSTSASHLDTFQEEETSKPNSTASGKQETFSKAIKRDSQTSNIPSVTSATHSLKTDKSKSAGTETSAKPNETSDSQSRKKDTLVTTPTETIQESAEKSELNDSSQSDILSLLPHKNGSNSPKDAEIENLEMKDISESPISSEELNDSDQVDEGNSYMCNSSCTFNTTPSQKNINSVNDICKKRYTECSSQSCNNIMSTNNSLPETFSAHSVKDNFSNLNSSPKGKTGNSALKTLPKDQNVSLASVLNTKKGIEDETLTSDSESAVLSGNTSDGTTRPKAQLSSESSCNNVQTEHTQNPSPSAVTPLSPELTASVLSSKVPTVGTKEISLSNEEDDHSKTESWKIKNLELQDREERPGKEKIYLVKESKLENNSPQEDSEQTIKCALNTSYQTEAAVESAWKVTESLEDSSDAQKEESNSMILSSYLSKCNENTSPRNQISPVLNEIPANNKEEEIKNSSNLCSTEYEKVPENWLHKEDHQVTNGTTLASVDNCTEKQESENISSENATVESRNEAHLLPNQEDKGKVKSTSSLNEFSETSSCAPDNSVTRNSKEQRHLKSKEFSLSPDLTKVDSFNDERDSADSLNSNIHSDSNTSNVSVKEESIHDEDSENSKQVILTENTAEQEVSPENSKIEESINHSQQITKDSEKQATVSSESNTSDKENDVNNPNECKELGMELIISIDRKKSKDCSNVAPTVLISQEYNKPILDGNVRKVGNMTLFSGDKTICSNLEIQLNSEKHKSIGSVNIYQGAQKFMVQASELGSISSKDQVLSWAAERGDNLSGPGNMLLSGDKVISTNVSTLEVLGRVDPRKKNSGSVKLNLVDSKKGLVCSVKEILQVTSSESVSIPASSILAKSLSPNSKRSFLSNEKAARYTNSSVLMSPAPDNSSTVTRSENSLPSSSVVNNSPRPKGQSPISCTESIQNRIPCGSKVGKTSVFNNQAQRPQSINDWKSSQPVPTTHNNYLFSAKSIKGVIVYVNHSRPNKPVFCPNPKNQFEVINSNVYHACPGKNVCIETYKFQCLQNKTQLAAKTIAKNSQLPTGHSKYLTGFQRDTESKGFTFHTFNCPVHKDFPPSSLLVPNTLGFNQQDGKDYIMVNGSERVQFNQNTNLTVSTKKIHENVEYMKKYFHSQPSINQNKPTSDHLQSHKPQEKENVLGLSEVQILPKKKKLIKQKLNSLAEEKRNLHIESAEELLNNLSSELNELSPEENIKNLIEKPIDLSTEITKLNHHNNQHKNLVEQDWKETGKNRNNNYDTTQKEIAQLAMESFVYDPTNRLIRLWKDTNENNKKIRGVNHQVVSELEKKLEVEKKQQNPWSDCVSCLDSDETEIILVKQQSELLNLLVDNSMNTKKDSEKKPTFLYQNFDKDLVDSNPQKGVLKDFIEKILNNRFQETEEDDSNWTQDQNEGEMTVSSPNVYKDAPPHVQPKGQDVSISHKKMKNFEVKTSTKTENDGPKVKEEQDQENSNSVSCQEKHDKYNDLTYSHSEEDEQSTKHKDNASAPYFDKVLKFMDQHPNKKVECSELSYNEENKEKCSKKECGKSLTSEQSELSGEVNSDSWNKENINCVNLEKRPSVEHPNASKPGTCSVHISRNCPNKEKILKESTKKACHDSATIYPTSSDQTENPYLNSNCPPKNSSICLQEIMEPKFQDTVQSEKENVQDKVESSQKACTSQKKCNSSLMISCIDKPKNPPKAQDKKLFTGKTEMGQSASVNLNVSLQEPNKYQVEKDLRNDIITKQLQMLSNKEYPNLTKKEKINCEEDMVLTTEGSTKCQNYISQCENHVPSKCCDKVKNNVCTKEDSTCQEKSKQGCLNSSQQNDEQNKSFCVEKVPYLDKLSAEKPFQNKCEEGCEKGSLQNIHSVQEEKKNDQETCLVSSKDNKSWDFIEASNKENNDKINKQCQEKDDNLNKSISSHESKPIPDGKEVGLLEFHNNKSVSKEHQNNKSVENSNKTVSESDKNSITLPNVTSGNINGGSFSENCSCLDEEKTCSKQDKSKHTSNISSAVGNNGSNSNGECLTDTENDDVNKSNKSKFIGLDSNKTSENHPYYEEMGINQDESSSSSQKTQVGQGKNISVNSNKGHNKAVEPKQEKYNKLPIDINVSPVTAKKVNLELQFQQNKCTSSIISKESGNIKGSVENHGQKKETSQNIKDKIQKTESQLENGSNIQLRSMNKTKASSSENMNSIPSEKKSPCKILQAKLQEEINNKLSSPNHLVAKSDSKNIPYKANKTEGIDNPCTSENKVLWKQNKEPVEKTSTSTDEKQNENVNQERTCPTGFQTASNKEQNKVHVDCKESKSKADKTINSSDLKSECINQEKNQNVSPVTSEETQNKNLSESNLRSNRSDPVVQKRDETTSLQTLISKEFRQASFPSHIHSKSGLYSEPENWFQGPCDSCPPRENVQTSQGSISREVNSGNNQCNHGNVKNVVKPNKEPVELENKSTSAINSKDPKSKFDKCLIENTKKNGSGVRKLNRPCNKERVSGTTLKPKGNTLSLPIDHISGKKDLSHFPSTSLKSEETSLCSQNLNKTNKNEDSGCKPNTFENQGLQGKNATFEVINTENKINDSCQKSKLNHSRNPQMSESKMNGKLYSENLVEGKSTCVENSKATLSSKENKSSSGDVSSKENVHSGQSTKRLHYNPMDTESQNDVHNITDLRCNFSHPLPPHIQKEVTSKESKESKVSQNTAFQYSSKKHFPTVKASTVDSQKGLQENTNSSNEETSSEGKPTQVTVYLKEKENKATQEHKNTNNKSKGLKDNFSLPNSTCQKNNPDEIDITCAKDNVNCEMDPKSEINKQRMKETSLPSDNKEENLSCKVPDLCSKESKTEDQNFNIKKPSKNSAPSALQVTVNTEHSGAPRLDENKDQDSGKKLNKEKTLTYYESNDLPSCSQPSSERTLNTSHGDPRNIPSCQKGSECSCESKSLVCHKESISKNRSMSKDVPISKENNINLIHSGKGQHDSVVSKQTINMEIHLPNSKSQTPDVSLSETNCKGQMMSGKENVDKGSGVSMGIVHSSKCQEAITNDKEIKCKVPILKGVQKESSCSSETKETTVNKDSKCEGKEKISNHFTFPSKANLPVNESKNHLDAQHSNSHIFSQLIPNVPLTEANMTIETSKTLECSKSQTECHTKVGTELNSKCETGRKNITNQYISTPNCKDLNIESTSKDFTKNCSDGHKHNIPDSNNQFFINDNSGSKMTENDSFKGCSNAYMSKSKSCTGPSTVYSKTEHMLAHKQVKTETVNSEKNKNNDFFSKEHTMSKATKFFSKTDDCSISRQLPSGSLQIHEKCSMENEKCNKDIPNEKVSDKCKESTSKAISPENIQLNNTREESNKKVSSKDSPFCNKVQKINDCESGKQPVFHGKEITPFKSGECPGKIKNDTTFIYEKCKVDLEQTKATKVNLPKSSTPLSCNIDCSCETPLNKSNTSCENRPHLNENKDKSVQNKETTVKRCLWDDISCNNEKTVSSREENVNMKRVKEENMNNKDGAGVLNGNNKNNTNKKDCEKENSCEVKEEATISFSVPTSNKDNTVNKAKNSTNEKLMNMKEENCQQIGEKINAVGAVQGTQMGCAENFISDNKEMKCSENDKLNMRSSGHCQDKQTETLDMKSGAKMPTQNFSKMKDGNETVRDCEHSKEMVLSKEKDLEKQNITDQKKLELDKSTESKESKELTEEKNKLNDCDNPTVKQKCSKKETEIASKDAKVSSITESVVSSVEAIKSKGENKKKSISHINKEKKFKFSLLPISPVDCLKTDNKCSEKEKKLQFSQVNSSKKQSKTVVDCKENKVPAGKETENSTSKDHKQFSVQVDNKISRKISVVESPQMSQKKEDFSNKSKLCEYKTDNVNKDKNTSNQDQNVMDDCNELRSDNTENQNKTSKTQNQQTAYDPFVSIFPPKKCSTPVGTFDMNDEDENVYTVSENSLGKSKRDITSVDENSNVISSTENQAGSRPSSTSMECVTCNDTKPSPEINEDKVPLKGTSCPQAHFNADFTCVICKETIPVEGKGKTVFKGLYFCEFCLKYMKSREIRELHRCTRHMACSCFVASLSCSGKKGYEMVHKGQHHPEEDCSKLTACFARPNSDTTKKRGKIFRQMVAEMRRLEKGHDSVWNRMSPGKSSRTVSDISVSSTETQQTKTDQVPNKAKVSKSISVEENTLNKVEPEKVLKQADVRPKSKGHLIEIDGLNGGTHWFSYMDFDSLQPLRCPVLGNGHTARGLRKVDLTPSLTKTLKRKHPNSILCCKKRIFRRNVPRDEFNLSESSDEFLAVRHSKSSLENRNSLGKGRITTLNVQNYETLYKIYLTTQDDGSVYMRELLTHGAFFPESLPQLSYDSRFQRLYRLRTRELHKCCIYQLNLSSAHKFNVESRSLNNTVKVEMQNNQLLKTNMPGFIEGVIKASSKTDIIEKSPKESCIKNQVAKTTANHWYYQNRLRSLKSGATNASGYMRPIA"
});

// Sample Disease Data
MERGE (d1:Disease {
  id: "MONDO:0007254",
  name: "Li-Fraumeni syndrome",
  description: "A rare, autosomal dominant cancer predisposition syndrome characterized by early-onset of multiple primary cancers."
});

MERGE (d2:Disease {
  id: "DOID:1612",
  name: "Breast cancer",
  description: "A common malignancy that arises from breast epithelial tissue."
});

MERGE (d3:Disease {
  id: "DOID:1793",
  name: "Pancreatic cancer",
  description: "An aggressive malignancy arising from pancreatic cells with poor prognosis."
});

// Sample Drug Data
MERGE (drug1:Drug {
  id: "DB00398",
  name: "Olaparib",
  description: "PARP inhibitor used for the treatment of BRCA-mutated advanced ovarian cancer",
  mechanism: "PARP inhibitor"
});

MERGE (drug2:Drug {
  id: "DB11748",
  name: "Rucaparib",
  description: "PARP inhibitor used for the treatment of ovarian cancer",
  mechanism: "PARP inhibitor"
});

// Sample Variants
MERGE (v1:Variant {
  id: "P04637_R175H",
  name: "TP53 R175H",
  type: "missense",
  location: 175,
  original_residue: "R",
  variant_residue: "H",
  effect: "Loss of function",
  clinical_significance: "pathogenic"
});

MERGE (v2:Variant {
  id: "P38398_R1443X",
  name: "BRCA1 R1443X",
  type: "nonsense",
  location: 1443,
  original_residue: "R",
  variant_residue: "X",
  effect: "Loss of function",
  clinical_significance: "pathogenic"
});

// Sample Protein Interactions
MERGE (p1)-[:INTERACTS_WITH {score: 0.950}]->(p3:Protein {
  id: "Q00987", 
  name: "MDM2", 
  description: "E3 ubiquitin-protein ligase that mediates ubiquitination of p53/TP53"
});

MERGE (p1)-[:INTERACTS_WITH {score: 0.850}]->(p4:Protein {
  id: "P38936", 
  name: "CDKN1A", 
  description: "Cyclin-dependent kinase inhibitor 1"
});

MERGE (p2)-[:INTERACTS_WITH {score: 0.910}]->(p5:Protein {
  id: "Q06609", 
  name: "RAD51", 
  description: "DNA repair protein"
});

// Disease Associations
MERGE (p1)-[:ASSOCIATED_WITH {evidence: "numerous studies"}]->(d1);
MERGE (p1)-[:ASSOCIATED_WITH {evidence: "strong"}]->(d3);
MERGE (p2)-[:ASSOCIATED_WITH {evidence: "strong"}]->(d2);

// Drug Targets
MERGE (drug1)-[:TARGETS {mechanism: "inhibition"}]->(p2);
MERGE (drug2)-[:TARGETS {mechanism: "inhibition"}]->(p2);

// Variants
MERGE (v1)-[:VARIANT_OF]->(p1);
MERGE (v2)-[:VARIANT_OF]->(p2);

// Additional Sample Proteins
MERGE (p6:Protein {
  id: "P38398_BARD1",
  name: "BARD1",
  description: "BRCA1-associated RING domain protein 1"
});

MERGE (p7:Protein {
  id: "P24385",
  name: "CCND1",
  description: "G1/S-specific cyclin-D1"
});

MERGE (p8:Protein {
  id: "P27361",
  name: "MAPK3",
  description: "Mitogen-activated protein kinase 3"
});

// Additional interactions
MERGE (p2)-[:INTERACTS_WITH {score: 0.980}]->(p6);
MERGE (p1)-[:INTERACTS_WITH {score: 0.700}]->(p7);
MERGE (p7)-[:INTERACTS_WITH {score: 0.600}]->(p8);

// Additional diseases
MERGE (d4:Disease {
  id: "DOID:162",
  name: "Cancer",
  description: "A disease of cellular proliferation that is malignant and primary, characterized by uncontrolled cellular proliferation, local cell invasion and metastasis."
});

MERGE (d5:Disease {
  id: "DOID:14566",
  name: "Disease of cellular proliferation",
  description: "A disease that is characterized by abnormally rapid cell division."
});

// Additional disease associations
MERGE (p1)-[:ASSOCIATED_WITH {evidence: "strong"}]->(d4);
MERGE (p2)-[:ASSOCIATED_WITH {evidence: "strong"}]->(d4);
MERGE (d1)-[:SUBTYPE_OF]->(d4);
MERGE (d2)-[:SUBTYPE_OF]->(d4);
MERGE (d3)-[:SUBTYPE_OF]->(d4);
MERGE (d4)-[:SUBTYPE_OF]->(d5);